version: "3.1"

services:
  app:
    image: 'docker-chatbot:latest'
    build:
      context: .
    ports:
    - 8082:8081
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5423/chat
      - SPRING_DATASOURCE_USERNAME=vnikulshin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=vnikulshin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_BD=chat