version: "3.1"

services:
  app:
    image: 'chatbot:0.0.1'
    build:
      context: .
    ports:
    - 8082:8081
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/postgres
      - SPRING_DATASOURCE_USERNAME=vnikulshin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    container_name: db
    volumes:
       - db-data:/var/lib/postgresql/data
    ports:
       - 5433:5432
    environment:
        - POSTGRES_USER=vnikulshin
        - POSTGRES_PASSWORD=admin

volumes:
  db-data:



